name       : broadcom-sta
version    : 6.30.223.248
release    : 1
homepage   : http://www.broadcom.com/support/802.11/linux_sta.php
source     :
    - http://www.broadcom.com/docs/linux_sta/hybrid-v35_64-nodebug-pcoem-6_30_223_248.tar.gz : 3d994cc6c05198f4b6f07a213ac1e9e45a45159899e6c4a7feca5e6c395c3022
license    : Broadcom
summary    : Broadcoms IEEE 802.11a/b/g/n hybrid Linux device driver
builddeps  :
    - kernel-headers
description: |
    Broadcoms IEEE 802.11a/b/g/n hybrid Linux device driver
setup      : |
    %patch -p1 < $pkgfiles/fix-alloc-netdev-for-newer-kernels.patch
    %patch -p1 < $pkgfiles/no-warnings-as-errors-for-date-time.patch
    %patch -p1 < $pkgfiles/update-for-linux-3.15.patch
build      : |
    %make
install    : |
    %make_install
    install -D -m 755 wl.ko %installroot%/lib/modules/`uname -r`/kernel/drivers/net/wireless/wl.ko