name       : broadcom-sta
version    : 6.30.223.271
release    : 65
homepage   : http://www.broadcom.com/support/802.11/linux_sta.php
source     :
    - http://www.broadcom.com/docs/linux_sta/hybrid-v35_64-nodebug-pcoem-6_30_223_271.tar.gz : 5f79774d5beec8f7636b59c0fb07a03108eef1e3fd3245638b20858c714144be
license    : Distributable
summary    : Broadcoms IEEE 802.11a/b/g/n hybrid Linux device driver
component  : kernel.driver
builddeps  :
    - kernel-headers
    - kernel-modules
description: |
    Broadcoms IEEE 802.11a/b/g/n hybrid Linux device driver
setup      : |
    sed -e "/BRCM_WLAN_IFNAME/s:eth:wlan:" -i src/wl/sys/wl_linux.c
build      : |
    KERNEL_VERSION="4.4.16"
    %make -C /lib/modules/${KERNEL_VERSION}/build M=`pwd`
install    : |
    KERNEL_VERSION="4.4.16"
    %make_install
    install -D -m 755 wl.ko %installroot%/lib/modules/${KERNEL_VERSION}/kernel/drivers/net/wireless/wl.ko
    install -m 0755 -d %installroot%/etc/modprobe.d
    MFILE="%installroot%/etc/modprobe.d/broadcom-wl.conf"
    echo "blacklist b43" > $MFILE
    echo "blacklist ssb" >> $MFILE
    echo "blacklist bcma" >> $MFILE
    echo "blacklist brcmsmac" >> $MFILE
    echo "blacklist brcmfmac">> $MFILE
