name       : broadcom-sta
version    : 6.30.223.271
release    : 274
homepage   : http://www.broadcom.com/support/802.11/linux_sta.php
source     :
    - https://docs.broadcom.com/docs-and-downloads/docs/linux_sta/hybrid-v35_64-nodebug-pcoem-6_30_223_271.tar.gz : 5f79774d5beec8f7636b59c0fb07a03108eef1e3fd3245638b20858c714144be
license    : Distributable
summary    :
    - Broadcoms IEEE 802.11a/b/g/n hybrid Linux device driver
    - common : Common components for broadcom-sta drivers
    - current : broadcom-sta for linux-current kernel
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    Broadcoms IEEE 802.11a/b/g/n hybrid Linux device driver
component  :
    - kernel.drivers
    - current : kernel.drivers
builddeps  :
    - pkgconfig(libelf)
    - linux-lts
    - linux-lts-headers
    - linux-current
    - linux-current-headers
rundeps    :
    - broadcom-sta-common
    - current :
        - broadcom-sta-common
permanent  :
    - /lib/modules
patterns   :
    - common : /etc/modprobe.d
    - current : /lib/modules/*.current
    - modaliases : /usr/share/linux-driver-management/modaliases
setup      : |
    %patch -p1 < $pkgfiles/linux47.patch
    %patch -p1 < $pkgfiles/linux48.patch
    %patch -p1 < $pkgfiles/linux411.patch
    %patch -p1 < $pkgfiles/linux412.patch
    %patch -p1 < $pkgfiles/0001-shared-Support-Linux-4.14.patch
    sed -e "/BRCM_WLAN_IFNAME/s:eth:wlan:" -i src/wl/sys/wl_linux.c
    pushd ..
    cp -a build lts-build
    cp -a build current-build

    # linux-current specific patches
    pushd current-build
    # Gentoo patch
    %patch -p1 < $pkgfiles/4.15.patch
    %patch -p1 < $pkgfiles/linux51.patch
    %patch -p1 < $pkgfiles/linux56.patch
build      : |
    pushd ../lts-build
    KERNEL_VERSION="%kernel_version_lts%"
    %make -C /lib/modules/${KERNEL_VERSION}/build M=`pwd`

    pushd ../current-build
    KERNEL_VERSION="%kernel_version_current%"
    %make -C /lib/modules/${KERNEL_VERSION}/build M=`pwd`
install    : |
    install -m 0755 -d $installdir/etc/modprobe.d
    MFILE="%installroot%/etc/modprobe.d/broadcom-wl.conf"
    echo "blacklist b43" > $MFILE
    echo "blacklist ssb" >> $MFILE
    echo "blacklist bcma" >> $MFILE
    echo "blacklist brcmsmac" >> $MFILE
    echo "blacklist brcmfmac">> $MFILE

    pushd ../lts-build
    KERNEL_VERSION="%kernel_version_lts%"
    install -D -m 755 wl.ko $installdir/lib/modules/${KERNEL_VERSION}/kernel/drivers/net/wireless/wl.ko

    pushd ../current-build
    KERNEL_VERSION="%kernel_version_current%"
    install -D -m 755 wl.ko $installdir/lib/modules/${KERNEL_VERSION}/kernel/drivers/net/wireless/wl.ko

    # Let LDM know about our aliases
    install -D -m 00644 $pkgfiles/broadcom-sta.modaliases $installdir/usr/share/linux-driver-management/modaliases/broadcom-sta.modaliases
